export const inviteCopy = {
  defaultDate: "2026-06-27",
  defaultTime: "19:30",
  ask: {
    title: "Дорогая Юлия, можно украсть у тебя один вечер?",
    lead: "Поиграем в нарды и разденем бомжа.",
    yes: "Да, забирай",
    no: "Нет",
    noReplies: [
      "Мисклик?",
      "Точно нет?",
      "Подумай еще",
      "Не верю",
      "Жму жалость",
    ],
    finePrint: "Отказ можно обжаловать у меня лично, но я буду смотреть очень жалобно.",
  },
  confirm: {
    title: "Не может быть) Не ожидал",
    lead: "Парочка вопросиков и считай, что договорились",
    button: "Погнали",
  },
  dateTime: {
    title: "Выберем тайминг",
    lead: "Я подстроюсь, но и ты не наглей, ограничений в пикерах нет.",
    dateLabel: "Дата",
    timeLabel: "Время",
    button: "Дальше",
  },
  dressCode: {
    title: "Дресс-код",
    lead: "Не является рекомендацией и публичной офертой.",
    button: "Запомнил",
  },
  food: {
    title: "Что берем за настроение?",
    lead: "Можно выбрать еду, а можно оставить мне поле для маневра.",
    button: "К итогам",
    captions: {
      pizza: "Тебе лишь бы пожрать",
      sushi: "Чин чан чон чиино",
      burger: "Две булки, три котлеты, четыре топпинга",
      pasta: "Романтик... ",
      ramen: "Попа будет гореть",
      surprise: "Опасно, я же ебнутый",
    },
  },
  review: {
    title: "Уверена?",
    lead: "Если все выглядит вкусно и подозрительно мило, отправляем мне план.",
    button: "Да, отправляй ему",
    sending: "Отправляю...",
    emptyNote: "без особых пожеланий",
  },
  secret: {
    title: "Секретный бонус",
    text: "Сертификат на одну внеплановую обнимашку. Срок действия: пока я рядом.",
  },
  success: {
    title: "План принят",
    leadPrefix: "Будь готова к",
    foodPrefix: "жрём",
  },
  dressOptions: [
    {
      value: "pretty",
      label: "Красивая как всегда",
      caption: "сложно ошибиться",
      icon: "crown",
    },
    {
      value: "hot",
      label: "Режим проститутки",
      caption: "опасно красиво",
      icon: "sackDollar",
    },
    {
      value: "hobo",
      label: "Бомж режим",
      caption: "уютно, дерзко, без понтов",
      icon: "dumpsterFire",
    },
  ],
  foodOptions: [
    { value: "pizza", label: "Пицца", icon: "pizza" },
    { value: "sushi", label: "Суши", icon: "fish" },
    { value: "burger", label: "Бургер", icon: "burger" },
    { value: "pasta", label: "Паста", icon: "utensils" },
    { value: "ramen", label: "Рамен", icon: "bowl" },
    { value: "surprise", label: "Сюрприз", icon: "gift" },
  ],
};
